title:  "情書"
email: wenlzhao@gmail.com
description: "everyday explorer"
baseurl:     ""
url: "http://muyun.github.io"
author_name: zhaowenlong
github_username:  muyun
disqus: muyun

permalink: /:categories/:title.html
#destination: ./_site
lsi:         false
port:        4000

highlighter: rouge
markdown: kramdown
permalink: pretty

kramdown:
  input: GFM

maruku:
  use_tex:    false
  use_divs:   false
  png_dir:    images/latex
  png_url:    /images/latex

#baseurl:     /blog
