destination: ./_site
lsi:         false
port:        4000
highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["highlight", "fenced_code_blocks", "autolink", "tables", "underline", "strikethrough", "superscript", "with_toc_data", "prettify","no_intra_emphasis"]

permalink: /:categories/:title.html
#gems: [ delicious ]
permalink:   date
maruku:
  use_tex:    false
  use_divs:   false
  png_dir:    images/latex
  png_url:    /images/latex

#delicious plugins 
#gems: [ jekyll-plugins ] 
  
#baseurl:     /blog

title:  "情書"
description: "by muyun_"

author_name: muyun_
author_email: wenlzhao@gmail.com
